# **********************************
# * Parameters for metemirge pipeline *
# **********************************

# List of files
list_files: "ref_files/list_files.txt"

# EMIRGE parameters
input_dir: "data/fastq/"
project_dir: "output/project/"
fasta_db: "data/silva/SILVA_132_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta"
bowtie_db: "data/silva/SILVA_132_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed"
max_read_length: 100
insert_mean: 240
insert_stddev: 100
num_iter: 5
num_iter_str: "05"

# Number of threads
num_threads: 28

# BLAST parameters
blast_db_dir: "data/blast_db/16S/"
database: ["16SMicrobial","ure_16s"]
evalue: 1e-05
max_target_seqs: 10
outfmt: 6
out_columns: "qseqid qacc qlen sseqid sacc slen stitle qstart qend sstart send length evalue bitscore pident qcovs nident mismatch positive gaps qframe sframe staxids sskingdoms"

# Parse BLAST parameters
silva_taxdb: "data/taxonomy/silva_taxonomy_v132.sqlite"
ncbi_taxdb: "data/taxonomy/ncbi_taxonomy.sqlite"
percent_identity_threshold: 80
query_coverage_threshold: 80

# Select best hits from multiple databases ##
db_priority: ["ure_16s","16SMicrobial"]
num_best_hit: 1

